### ISSUE TITLE
Google related sites are added

### ISSUE THREAD

**Issue by danny0838** [elliotwutingfeng/SpamdexingSites#2]
857c838302e579ef3aec930b06ee275a150b37fb: added google.fr, google.it, googlevideo.com

Is there any wrong about these google-related domains?

**Comment by neilyhy** [comment]
@elliotwutingfeng 
https://github.com/elliotwutingfeng/SpamdexingSites/commit/bb000c0bbc54eaba26e56527f3994856055ba2e1 removed google.fr and google.it, but left googlevideo.com.
googlevideo.com is what youtube uses in the background, this is blocking all of youtube.

**Comment by danny0838** [comment]
I don't get it. Why block all of YouTube? You mean YouTube is spamming?

**Comment by elliotwutingfeng** [comment]
Dear all, thank you for the reports and apologies for the delay. I have unblocked the remaining Google-owned domain. 

It was caused by spam sites containing redirects to legitimate Google-owned pages. I will be tweaking my allowlist to prevent other major cloud services from being listed as well.

**Comment by danny0838** [comment]
Thank you.
